### ISSUE TITLE
_lookup_cast_type removed in Rails 7 alpha

### ISSUE THREAD

**Issue by afomera** [palkan/store_attribute#17]
### Tell us about your environment

**Ruby Version:** 2.7.2

**Rails Version:** 7.0.0.alpha (from GitHub)

**PostgreSQL Version:** 13.3

**Store Attribute Version:** (Latest from GitHub)

### What did you do?
We've started looking at using our application at work using Rails 7 from GitHub, while using `store_attribute` in our models. In doing so, it raised some errors from underlying changes to ActiveRecord.

For full transparency, this is how a few of our store_attribute calls look:

```
  store_attribute :greeting, :title, :string, prefix: :greeting
  store_attribute :greeting, :description, :string, prefix: :greeting
  store_attribute :greeting, :video, :json, prefix: :greeting
```

### What did you expect to happen?
The error to not be raised :) (though to be fair, it makes sense _why_ the error happens)

### What actually happened?
An error was raised (both in the browser and the Rails console)

```NoMethodError: undefined method `_lookup_cast_type' for #<Class:0x00007fd1b53d5430>```

I tracked it down by removing the `store_attribute`s in our model, and things behaved like expected, when I dug deeper into the gem source I believe this is the only occurrence of using the removed method from Rails 7. https://github.com/palkan/store_attribute/blob/2708e7f481f75275485ad7e4458b5f5b7438f742/lib/store_attribute/active_record/store.rb#L135

Here is the PR with the removal of this method from Rails: https://github.com/rails/rails/pull/39929/files#diff-2a6a5a31a6210a1e7036784fb31c738e1d2874bb5ae123d03737db02cb198876L290-L300

I wasn't quite sure how would be best to fix the gem for backwards compatibility, so thanks in advance!

**Comment by palkan** [comment]
Thanks for reporting!

ActiveRecord changes fast; let me take a look...

**Comment by palkan** [comment]
Should be fixed by https://github.com/palkan/store_attribute/commit/6848ccb067ddcae58afeec20796662dd36d46ad9

Could you please check?

(I'm not going to publish a release yet; let's wait at least for the Rails 7 beta).

**Comment by afomera** [comment]
Thanks @palkan I've confirmed that https://github.com/palkan/store_attribute/commit/6848ccb067ddcae58afeec20796662dd36d46ad9 does indeed fix Rails 7 support. Things seem to be working great as far as I can tell now. 

Appreciate the fix!
