### ISSUE TITLE
Validators are not working as expected on stores

### ISSUE THREAD

**Issue by tomshy** [palkan/store_attribute#30]
**Ruby Version:**
Ruby 3.0.0
**Rails Version:**
Rails 7.0.4
**Store Attribute Version:**
1.0.0
### What did you do?
use validators on store
### What did you expect to happen?
validation should be effected
### What actually happened?
validation not happening - atleast the presence validator is not working well

### Example
```ruby
store_accessor  :store1,
                  :store1_key
store_attribute :store1, :store1_key, default: 'value'

validates :store1, presence: true
```

**Comment by palkan** [comment]
Hey!
You MUST specify the type for `store_accessor`, otherwise default is not used, so:

```ruby
store_attribute :store1, :store1_key, :string, default: 'value'
```

See also https://github.com/palkan/store_attribute/commit/c2650d895033cb89c9f3758a683dc9338f64b370

**Comment by tomshy** [comment]
Hey Palkan, validation on the store itself fails as shown in my example code. I have the syntax captured well with the type of `store_accessor` specified

**Comment by palkan** [comment]
> validation on the store itself fails as shown in my example code

It works as well (if you define the store attribute type)

(I've updated the test case: https://github.com/palkan/store_attribute/commit/2d1923ebd3850786a43e54cb2d148de5ea977e6c)

**Comment by tomshy** [comment]
Can't I validate the existence of the store itself?
