### ISSUE TITLE
[Feature request] Add suffix and prefix to store_attribute

### ISSUE THREAD

**Issue by mario-amazing** [palkan/store_attribute#33]
Could you add to store_attribute the same prefix and suffix functionality as in `store_accessor`?
Thanks in advance

**Comment by palkan** [comment]
It has been added in v0.8.0. Which version do you use?

**Comment by palkan** [comment]
Then it should work; can you provide an example of not working functionality?

**Comment by mario-amazing** [comment]
I've checked and everything works fine!
maybe you can add it to README?

**Comment by palkan** [comment]
Makes sense. Added
