### ISSUE TITLE
Undefined local variable or method `attributes_to_define_after_schema_loads`

### ISSUE THREAD

**Issue by benone** [palkan/store_attribute#39]
In a [recent commit](https://github.com/rails/rails/commit/e0a55b038f7f2f50d1467876558be183be6cedaa) `attributes_to_define_after_schema_loads` was removed from ActiveRecord. This change caused an exception

### Tell us about your environment
**Ruby Version:**
3.2.2

**Rails Version:**
main branch

**PostgreSQL Version:**
16

**Store Attribute Version:**
1.1.1

### What did you do?
I upgraded to latest rails version

### What did you expect to happen?
It should have worked as expected

### What actually happened?
An exception was raised

**Comment by palkan** [comment]
Thanks for the report! We'll check and fix.
